In [1]:
import pandas as pd
df = pd.read_csv("files/Global Population Trends(2016-2022).csv")
df

,Country,Year,Total Population,Urban Population,Rural Population,Population Density,Life Expectancy,Birth Rate,Death Rate,Fertility Rate,Infant Mortality Rate,Growth Rate
0,Afghanistan,2017,-,-,-,55,63,37.342,7.027,5.129,49.4,-
1,Afghanistan,2018,"36,686,784","9,353,296","27,333,488",56,63,36.927,6.981,5.002,47.8,3
2,Afghanistan,2019,"37,769,499","9,727,157","28,042,342",58,64,36.466,6.791,4.87,46.3,3
3,Afghanistan,2020,"38,972,230","10,142,913","28,829,317",60,63,36.051,7.113,4.75,44.8,3
4,Afghanistan,2021,"40,099,462","10,551,772","29,547,690",-,62,35.842,7.344,4.643,43.4,3
...,...,...,...,...,...,...,...,...,...,...,...,...
1068,Zimbabwe,2017,-,-,-,38,61,32.516,8.266,3.706,39.5,-
1069,Zimbabwe,2018,"15,052,184","4,848,158","10,204,026",39,61,32.074,7.972,3.659,38,2
1070,Zimbabwe,2019,"15,354,608","4,945,719","10,408,889",40,61,31.518,8.043,3.599,37.1,2
1071,Zimbabwe,2020,"15,669,666","5,052,214","10,617,452",41,61,31.009,8.132,3.545,36.6,2
1072,Zimbabwe,2021,"15,993,524","5,166,388","10,827,136",-,59,30.537,9.057,3.491,35.7,2

In [2]:
df.head(5)

,Country,Year,Total Population,Urban Population,Rural Population,Population Density,Life Expectancy,Birth Rate,Death Rate,Fertility Rate,Infant Mortality Rate,Growth Rate
0,Afghanistan,2017,-,-,-,55,63,37.342,7.027,5.129,49.4,-
1,Afghanistan,2018,"36,686,784","9,353,296","27,333,488",56,63,36.927,6.981,5.002,47.8,3
2,Afghanistan,2019,"37,769,499","9,727,157","28,042,342",58,64,36.466,6.791,4.87,46.3,3
3,Afghanistan,2020,"38,972,230","10,142,913","28,829,317",60,63,36.051,7.113,4.75,44.8,3
4,Afghanistan,2021,"40,099,462","10,551,772","29,547,690",-,62,35.842,7.344,4.643,43.4,3

In [3]:
df.shape

(1073, 12)

In [4]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [5]:
df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690
...           ...   ...              ...              ...              ...
1068     Zimbabwe  2017                -                -                -
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027
1                    56              63      36.927       6.981
2                    58              64      36.466       6.791
3                    60              63      36.051       7.113
4                     -              62      35.842       7.344
...                 ...             ...         ...         ...
1068                 38              61      32.516       8.266
1069                 39              61      32.074       7.972
1070                 40              61      31.518       8.043
1071                 41              61      31.009       8.132
1072                  -              59      30.537       9.057

     Fertility Rate Infant Mortality Rate Growth Rate
0             5.129                  49.4           -
1             5.002                  47.8           3
2              4.87                  46.3           3
3              4.75                  44.8           3
4             4.643                  43.4           3
...             ...                   ...         ...
1068          3.706                  39.5           -
1069          3.659                    38           2
1070          3.599                  37.1           2
1071          3.545                  36.6           2
1072          3.491                  35.7           2

[1073 rows x 12 columns]>

In [6]:
df1 = df[df['Total Population'] != '-']
df1

,Country,Year,Total Population,Urban Population,Rural Population,Population Density,Life Expectancy,Birth Rate,Death Rate,Fertility Rate,Infant Mortality Rate,Growth Rate
1,Afghanistan,2018,"36,686,784","9,353,296","27,333,488",56,63,36.927,6.981,5.002,47.8,3
2,Afghanistan,2019,"37,769,499","9,727,157","28,042,342",58,64,36.466,6.791,4.87,46.3,3
3,Afghanistan,2020,"38,972,230","10,142,913","28,829,317",60,63,36.051,7.113,4.75,44.8,3
4,Afghanistan,2021,"40,099,462","10,551,772","29,547,690",-,62,35.842,7.344,4.643,43.4,3
6,Albania,2018,"2,866,376","1,728,969","1,137,407",105,79,10.517,8.308,1.44,8.3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1067,Zambia,2021,"19,473,125","8,800,295","10,672,830",-,61,34.511,6.973,4.308,40.2,3
1069,Zimbabwe,2018,"15,052,184","4,848,158","10,204,026",39,61,32.074,7.972,3.659,38,2
1070,Zimbabwe,2019,"15,354,608","4,945,719","10,408,889",40,61,31.518,8.043,3.599,37.1,2
1071,Zimbabwe,2020,"15,669,666","5,052,214","10,617,452",41,61,31.009,8.132,3.545,36.6,2
1072,Zimbabwe,2021,"15,993,524","5,166,388","10,827,136",-,59,30.537,9.057,3.491,35.7,2

In [7]:
print(df1.describe())
print(df1.max())
print(df1.min())
print(df1["Total Population"].describe())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000
Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                  85
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                       5
dtype: object
Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                       -1
dtype: object
count         864
unique        864
top       105,870
freq            1
Name: Total Population, dtype: object

In [8]:
#2.8.	Выполните сортировку данных по нескольким критериям
df2 = df1.sort_values(by=['Year', "Country"])
print(df2)

                    Country  Year Total Population Urban Population  \
1               Afghanistan  2018       36,686,784        9,353,296
6                   Albania  2018        2,866,376        1,728,969
11                  Algeria  2018       41,927,007       30,451,166
15           American Samoa  2018           48,424           42,203
19                  Andorra  2018           75,013           66,058
...                     ...   ...              ...              ...
1052  Virgin Islands (U.S.)  2021          105,870          101,678
1057     West Bank And Gaza  2021        4,922,749        3,790,664
1062                  Yemen  2021       32,981,641       12,713,103
1067                 Zambia  2021       19,473,125        8,800,295
1072               Zimbabwe  2021       15,993,524        5,166,388

     Rural Population Population Density Life Expectancy  Birth Rate  \
1          27,333,488                 56              63      36.927
6           1,137,407                105              79      10.517
11         11,475,841                 18              76      24.074
15              6,221                242               -       0.000
19              8,955                160               -       7.200
...               ...                ...             ...         ...
1052            4,192                  -              80      11.800
1057        1,132,085                  -              73      28.236
1062       20,268,538                  -              64      30.544
1067       10,672,830                  -              61      34.511
1072       10,827,136                  -              59      30.537

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate
1          6.981          5.002                  47.8           3
6          8.308           1.44                   8.3           0
11         4.482          3.023                  20.6           2
15         0.000              -                     -          -2
19         4.400              -                   2.9           2
...          ...            ...                   ...         ...
1052       8.600           2.01                     -           0
1057       3.815          3.504                  12.8           2
1062       6.845          3.795                  46.7           2
1067       6.973          4.308                  40.2           3
1072       9.057          3.491                  35.7           2

[864 rows x 12 columns]

In [9]:
df1Fl = df1
df1Fl["Total Population"] = df1Fl["Total Population"].str.replace(',', "").astype(float)
df1Fl

C:\Users\User\AppData\Local\Temp\ipykernel_34764\2197704279.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1Fl["Total Population"] = df1Fl["Total Population"].str.replace(',', "").astype(float)

,Country,Year,Total Population,Urban Population,Rural Population,Population Density,Life Expectancy,Birth Rate,Death Rate,Fertility Rate,Infant Mortality Rate,Growth Rate
1,Afghanistan,2018,36686784.0,"9,353,296","27,333,488",56,63,36.927,6.981,5.002,47.8,3
2,Afghanistan,2019,37769499.0,"9,727,157","28,042,342",58,64,36.466,6.791,4.87,46.3,3
3,Afghanistan,2020,38972230.0,"10,142,913","28,829,317",60,63,36.051,7.113,4.75,44.8,3
4,Afghanistan,2021,40099462.0,"10,551,772","29,547,690",-,62,35.842,7.344,4.643,43.4,3
6,Albania,2018,2866376.0,"1,728,969","1,137,407",105,79,10.517,8.308,1.44,8.3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1067,Zambia,2021,19473125.0,"8,800,295","10,672,830",-,61,34.511,6.973,4.308,40.2,3
1069,Zimbabwe,2018,15052184.0,"4,848,158","10,204,026",39,61,32.074,7.972,3.659,38,2
1070,Zimbabwe,2019,15354608.0,"4,945,719","10,408,889",40,61,31.518,8.043,3.599,37.1,2
1071,Zimbabwe,2020,15669666.0,"5,052,214","10,617,452",41,61,31.009,8.132,3.545,36.6,2
1072,Zimbabwe,2021,15993524.0,"5,166,388","10,827,136",-,59,30.537,9.057,3.491,35.7,2

In [21]:

mx = df1Fl.sort_values(by=["Total Population"])
print("Название страны, которая имеет максимальную численность населения =",mx["Country"].iloc[-1])
print("Название страны, которая имеет минимальную численность населения =",mx["Country"].iloc[0])

Название страны, которая имеет максимальную численность населения = China
Название страны, которая имеет минимальную численность населения = Tuvalu

In [25]:
df1Fl.to_excel("files/ans.xlsx", sheet_name="Lab2")